apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kitten
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.90"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kitten
    image:
      name: vibioh/kitten
      tag: "202308051130" # {"$imagepolicy": "default:flux-kitten-api:tag"}
    config:
      GOMAXPROCS: "1"
      KITTEN_DISCORD_APPLICATION_ID: "959191057835393044"
      KITTEN_DISCORD_PUBLIC_KEY: 2a1eb3b4786bc5dbd59d1f8d35eb44f5243e959158ae75367f57e0d4f169ba47
      KITTEN_LOGGER_JSON: "true"
      KITTEN_REDIS_ADDRESS: redis:6379
      KITTEN_REDIS_DATABASE: "3"
      KITTEN_SLACK_CLIENT_ID: "2426300949335.3310973634019"
      KITTEN_TRACER_URL: otel-collector.observability:4317
      OTEL_SERVICE_NAME: kitten
    secrets:
      KITTEN_DISCORD_CLIENT_ID: AgB2BP/8Z/vJgcPxHedoahwu5Tq7kDq+ne1A9Ms1IOvptxk85wPu9LpAYXxKyFvWHErhjNr9qLNK7SiaFUvrz7lFHJUiQblUHeTqjUD9KRgzj3kMxrKO6is0jfx110S5X/xL3NV1k+7xyq6JSSHla/9CnxvCpDI5HEKLtOZGYPjnQKlubBOr+oi3Vt46JRdeWTexA8zxXGOXApdgEzimZhAn8kDbVoKLBqQ8vUIwrtK2rQ4cb64+RsMVQW/LzGFZ3qOknZ98T6zkS7qBWEK9BWw8ANjzMyR5d3ujZCaYK2efl2I5fGL9MoOZmtXObStfZrxQPZdP/Jvf7BoZqT0DOerODVCdzpG4+IlUz3Yetez+STKVxWe8TwKBDreKBUK1KOyDwa9kB6GtzJLvZal5AGguQrK/yBVLFanSfx2/2WX+9g74GXtiz2yPQGdCBnipgvpQdMOZVGgHGXZ9mYpFLR+uAMMjQdceXCeim9JZkleDmonSg0V56sJ6DSHFkaXHoxlfV6jrHIjrqyhhlSxtREfyLdKK+up5xl/od3nxMR61QHTZU/exN3TmyQaPdWpcXPJVfoGvMLMEiLPypABACiPH8IOKFWDN4VQNIgHptVW98eQThZ08OW58y6LXQFGwnzYk5o/EXfjkLVzKRouRfgW2jnnomH2g8/r7VgRcp95m6grP4KY2yP+eJjruyL/Ymi40p++B1z/byIfIe2WWU0wfxhA=
      KITTEN_DISCORD_CLIENT_SECRET: AgCHrlM/BSf550oYqM66SPpOUTRTT+o/eWQVX5WkfIbH6mUB3GRuHLxGt6VJnHper9Ct9ULMoFkcOXx6dsLDg6GOSW/q2kFTpOARtaZcHjdn8fB5RDi5nfzAEvq53hCoToSsHVr3rxw1GLv+c1elKWnLX/w9shUXET/hQBnLRLiBUjMx6vxqPuUkOyGh2PAvLIfFv59GEdCI28RNNCZVCXTbKsB3fA+aputDQPDapaDQSMCP+rBECp8NsT/NA5fu5H4gqA7virJ3VLr9RRxJSq4axMCoih3UhuYGegwOxSsUOFlE8ZbqNMMAnt70r7FxhnOtoOzvaDV7i3iQhRX32E/1OMDh4ImxIEEMMy0CElL//EYXpokXXHto9JvApqrMIRYGHokP4tOikAiS0Pe0PxM3dDizlTbnKaR0iGnOvflmRE7h3dvuM8y6lzhs7g5UbNQwFjOf/ueqyblCtGqgNpxxPJLdqgaMdawjoXfUarDNhMMj/VpJPjyJeaBgd0py7gf4Hb2mkr6q/lk/8XMnnToAFlxZo0QxUooXL+rUuDQSEfaCEaIX6u+6AtpfDgZxotz//QTh4xekaL032Il4ezg5+FHPyAy/P4JaA0CFehzy1vJLayjLznXxgbTmO2ucxDdgc2WOl/eIGmyE+fLPn8O3FAtfPKUbfmkmNb2hpQ2oGrE+ifwQeydu9AwmDhovahpmrgygO/TTXYweHIZMJ3UAqohNIfAVioSjR+Kw9fwoMw==
      KITTEN_REDIS_PASSWORD: AgBZETj8bQBj44w3kmIi75q+hp9195fx92iWfn9ERk//UsnFWu42QUBeF3SheunU4U9FDqfnQDMxkpUG33E2rELs5OyanW24XzzIbgGazx3aWdgrkqo4pmKmVRywTF+9dp86mK+4DQ4pdWFtpV4NZsLWbuEFqT4S+mSWveKdZmk87EEaVGtSh1hmCf1ycXwsKNzYJ3p1Cof7Ml+rLH7GN2XXxR5gppnohC0+BHIQvdno62iAz1nuU2NhK1IEcJ64zauZS1dLrr6C7EJwfqkVsiSD9U32wWd9pBMavM+OC1shy0au7njol+Kl5pXfbj+j1GI4tIeGt7LfTX6dyJF59IroSmYg9tggQRJqgsY+uF+YKM+2kcu83xtY/LBxcdiBDTfq7uLhm6mD1LsSH6b+VP1Vd+U4b+w935wY62DSoIzytZvn4qMfYs0MVZ1NdGwktOUzCv4pX84Fg/6aiXhgW72fH+kDimf3fc+NZKRDbza6BN8oJvsgTjQ5EjkChUTZJOBc1oRT08UPcD3hcX3LQhASbaEwaPss5VzcejFeB8lQ83w/ZCi0AfjD05zvyJXFLJ6L8GWk6CJjsAJj3zXHZ4koKZbHvVWo0RFfmga5cXSTorh72P+OHq2HtNbF8yQi2xDz6bIMKIvEUZzhdCBGMIs/YNICcipF18sz0568fZFTLfpAwUbxPq5mB18bStRXjI83iTYmUnBlR/XWxVWkdJ2dJSUaODlsHItgGmzd5NcuKbAlAo5A8cGLhLl5bEJ+2qW8IizMifzUKNciIwPCPGE=
      KITTEN_SLACK_CLIENT_SECRET: AgAsuXk4js1X7yQpsdsMQqrlQ13SiHXrFO/m1MMxSZurHvBRYweFn3o+0sb2kcOEpBBW2wR85c+BKmxkBtq7jwLgc5cavA93gLKi3ZOCN/zIMTScwDLXnUqL/ac8edC2UHKDtz2WoyJftBzCzhjP2OD5/0gf3fURgAnVyHXJ5tF4DrkcpK4g96xrpP7N4eU59LmxbVruBLv8OGU+fddH/3/zeYmR+2qUolwAIPvot3gb+bhe4Ur+Lug2NGl28n8I8DsUNqDVLxBgu/+wW9tUo5C4wF481fSf2F9SwFuekUVmE1Xdw8cJmIBgVsic7gkXlDHxZ8MZ6CZaPvQz8856LiYCDjVtsQSexp5E6qalcuxDQJZ7RXT2ND6uzzSjr1gj7Kkysn7uzl7bPF7yVdO4rPuwZfhdVzR/1xHCuPwYTFkUzRCI+WQeqL+Ji3hhEsj/7mHYgvPtHT9y6dNCon0QlB1aQOtGMloSeUwyR1Se94igLHh4a+vh7/ErRz1ImRVZzgnXVEP8wOZZRl+ZtnddCXd5c7SEyZ2NgOl6y5l2gRQrDxZ+2xj401utZWj8BAZIrF7HMOl660ErSEoRJMLHlXUDtOlQUProwDWx9KFdkCKmI7BEYQYmA26WzxHVe7PPH/PX66IhStwu/OAnKD7Nvw5/lvmHXAmy/BGjEC5EbwP1KxBSrTN8p1cG3keZ8o+X7/71ac5aRxSE5NdQL0aYSgjVigZQWlL4r+3Xx3BX3sesXw==
      KITTEN_SLACK_SIGNING_SECRET: AgAyL9TUl0VJJVVCdvr6AIdgzT5p16FyfeV/0NHUkDx8ECqw9OLU99yZ/0u7GUe47q3ajgBEUyIkU2HnPoSyqCGK7kjcrwudpW/jeUQd/NOu5Iw5e3gK7J+GuftGejoKajbGzuh4FEykoZSFvugKSNzb06qMJi3ZaNEWAxpnf6FWd+VHxQZQ7fhYstSV1+NBY+5XgUrtYwqRfagNuJKWVmB1FZfu4tP/0C1QzXLAZoaJB6bcSs2rSnxYvGwcwFVaxbzStrYKBqWRfdluWog0A4EGW7RLlAladBDp7VY1hQw5AT4JHqa+YdQz3J6npNfpjhYhI1kLdMCcVJw7L9/tuoyidMXDK1tg3VOnsYXGOsTblt8fAp+0zWJrDSuQvwp7dj9xGrNXqkNvM3zvl+QOLS18PoNv8GYi/wdgcNM6rQNRY/+QJk+RxfGy3FmaANr2z9A9wSeHIrESNOfcdZfsq7nl97HEdZ1ctu8zBidij2W2SfJ2jHu+2vVAxU8Dwo8EcCuTIPiJ51zETjsRSR+a/rupPC2Vmw5v8700FPOXYr27+9LjA5Vv7asm9iK2JJxseEQP0w4YkYSYk1pwYNypf3Wp+5dOGtzpaSuG+b1llizdupz5FirvHviVNZGesiMnUiFqCeh3OCohz7Nc8+fj6H0juMuYnpNLiyohPX6jlHb/mrKy9MKK4FlYReDPtuRr1ZJLHI+K9F17lvTiPvP+uCoQM4pnqI7ZY6A9tTRJLvq/GQ==
      KITTEN_TENOR_API_KEY: AgCgx5NYlY7wcD8ahGYnanAFp41nDmiacPntL4gD46P/nHIPQb7Gh11OBIjet0pZAldoHrO/zzw0v94Pe6DJHtSLNS5FshMbX+/GldVsx+gyo1TeBKxtfc9QAAeo2ig+r/us9J10RLddNp0l4C68CBYorEsxFnhhtFweVk4p/2y+3hHWItzsa/lD8QgtLi+WYNe32ImVZV5EXrg23ej6qicv5a74nm/jucDw50z+fluPoeLJqWUHSbOBtMhlQHimPUju0tkUGqMdvC+SP3zA/X/7usvmHqiorexQXuYMt7jn0Zo6FlfaqtwIXTDpAfl0+gXzhhA3jwL8N7/orA7R8ApMUIduEKRvgEmuH6fQS6cHOu2Kyv5O8Eex56SYCkdM/SaEDSeyPfAoVFCNzcv5R54K3sBB9UHU7kKfYxGS1sknOpXExNP6gfq7TlQ/iNdC1CsHp4cw2sZgJu6ZyqmPt2gbpbcseRD28Uc2kUVZbNDsetqlMQ/ipshpbqvKCHxHxETaJxXOC5vkJHCdn6RqoB/Dymf3l50txjn4Qf6DL1GB0DFs8Dn123j4eacIGnvBo7q2xP/l3BeZltYTUulVzr6Gw0Teafg0tsQC0D54ZB9tAfxXJ53D45nW6kg9usoKuUlHSQ/laxVHph/v+zhRXP+RRU1RqJQhsjV/HH+E49go97Uz16yfhuHDHIXyuXoWHkVmH02oMVS74pA4iR4j4JplnTSLKw4dww9i5iMMTMbj2uBk9nVIEW8=
      KITTEN_TENOR_CLIENT_KEY: AgAUyqMlEwGIcIIaIcWhm0jCLfXLdl0KOqpYINfvaTpuC3BCKXwMcFW/lwpWMxo1vXY6349BDkUUAcgy5B0RuDsrrG6qFwKIQOEgyy3zoPz6fCTV8Tg0VFNiFvAEGRIa2EWcjEG5Zl8+Sc12wEQ9I+R/3s/XHhVr8xNEnF5mzrqiNuXGI25Jz6FWd3ZLpd/b59QPc4j+nsZqbCmk7I16Zobb1BI491sN07aNPLsj/6RnxYTi9FHpTqfZrK99LmGGjCvQk6tZg+a/1nldKBE5g6xkpCrm3AsXF1LYVokAyZej1cKdaJSOGW7q5JUhXdMvC03+DBgxgZS5XMZlf6OKa53OgznZfi2C6pgL5c4BYdHARm5ZGkolkkipRL1QBfZSHPZcpMV2NG15ebzVCgs8laBu1bDLRHTCjt5IUDdSpgsTVukKmHKRsyE6zkISUGFcUEWL/U5Ao1fpxOqO+JeX8AmNOtWwUtjWDV0eX2fgRSx9g15kw7B2f8G2RijmIcJfJ/No/uPO3ZPFEIv4FQ553OdeUKWauKWDTTy+pV7YBcpjy98VpRyJahGZ6/wXw04J9z+qW0rZLz5LBsnwOCuEdh5B38hqOrsgoJYhbLk94u8A8nDESHXXsxLrM/S/fHIWWJmqX8xGXZZ/3L0+xqbZ53b88Pw/XWIsmSrpn3PoK5NzEtEMhmPQLMgHcVLpLgQKQ9BqWr6VfwM=
      KITTEN_UNSPLASH_ACCESS_KEY: AgCNtJx00kJ/fdLydxyIqtX33K/bQbEi1yLn5r5yi50+ewMMhQvBvewLGWtD4FHuGEW9ANWV0Q4p+SpKgc8vad8vI7KtGDtbAV6PHWxQJ+poZNEKOie8l2QL7d5qa9+PDaeTZPh2ZpZsE7m8qxHkqBOQ3T2uMPfIsfpQHKWfjR546q8YQgCG9ZILwJQtVuaxcVDItNqcO+BTETPi4jD8WfR7z8w2hNP3DkmEqu0oy5nsZrH9cajfNTMvDTfS7Fsp+aUnEIkqU1G4WoDOvnl9sbZtTRvByhNyN4rBO5VrhJX5MyrUi0w84dCXlF89fIFEm6Hv5aA9rUj4yHfPYwAFM7pYxiWegoET4CWKMMESCAfw3W3KC7C3gPJB26OAaZqzupqtzu2dXSapv+PesPSdF9ucH0QRk65AYrVSRCTdIF950ubMWiQdpKCQJXis+tmrY6Ca0YbJ7zppVnGkAOGHJERlmR02lfiGVExfqI5O+ygiQopqjAZxih1/wiRi0oMA5XqY19y8TkGU9CQwCxKypRcGjL70S8aaY46Y5o8CqAnoerzlDQ/wKWmr+BTKAHLV5JmPaqsYci8mm4WAQt8J49CqLbjiaZvVB4Bv73G/Yq39FRnt8yOBjAqfm0zDfqvJAgl4XGIfShFoeFct1UsI+Td4BzKAECHFHTJp/A35cG4KLnSbHdab5NZ+C20rO1iN+RNcfK6TwG4B1zixmP0wEaT57LTMOi6YmWEBNds/0vz1F2AZNlCnifT4vVNB
    ingress:
      enabled: true
      compress: true
      hosts:
        - kitten.vibioh.fr
    pprof:
      enabled: true
    resources:
      requests:
        cpu: 500m
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumes:
      - name: tmp
        emptyDir: {}
    volumeMounts:
      - name: tmp
        mountPath: /tmp
