apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kitten
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kitten
    image:
      name: vibioh/kitten
      tag: "202203291720" # {"$imagepolicy": "default:flux-kitten-api:tag"}
    config:
      KITTEN_LOGGER_JSON: "true"
      KITTEN_REDIS_ADDRESS: redis:80
      KITTEN_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: kitten
    secrets:
      KITTEN_REDIS_PASSWORD: AgCGUDWeTJcEINqtKDbac4wPHF1Inn1gspltV0a346/8OjAI2fgJCzOSmhalDpXg+HwtLm8BZErpn/hV2czJjfn8YQVEYwf2G6yrm/hODXZh4uiQBVbdzwEeFIk/+nrSfcKooz/IRTUuOKbxN/F/xJpeZb+AJ6/F7Agrcj/zFDwlRkayXvHHsCeJOShuVdWjAg5mg7oOkvDlYGRudGOe0Wyh36/N6a4APiUBctG4xU4X1gxicgY0wD128tHKYrGfMhK9nufz0jhycw8c4mZZNcn97L9d4EmNNb+xULbGrTWjpdCJt5o+G80enbx0yz4zq1ELGFj9tdoSR7zhV9Rm4yqsSZfqVfg2zKrpK2x1qOuZvVaVI3uPPuxvI7o4H1e6PViL6Dzk3fW/RaYt3GP77a4ROla2Teb9Rl8yFQf1hD4LkhiUeF6NPvEFZgcSeY5U0U/QGzGY0BPIEd+jrcEWJr9cIN2LRKhT3r4USqPad+hReTUo0vsE1VfGeUj5qBQXhI3uNKyWU6CD9ssK3GgAWRCglLdhSVJOiJkzWrN5iIamS49KaM+LbBBeEgyp6eDdykTQApJIYX17l8qTPhrmtaH5woGwH5tbdB0+0VTKXsGfxGo0VN5rUXIA5ghAfosMzb1GfO5vPKPVayDyBNxCkcmiTMpvmoURdMrSWiUqRYsxnAOIHVkir3lgnmLelsjIKzjd9a9QuZzVlqZ+syaqcscKrh4rDX3/lDIagzlAmb92ISfYbSK65Rsb6LpJkpgG2Vsilx9h7h1/knjPvt2/eR8=
      KITTEN_UNSPLASH_UNSPLASH_ACCESS_KEY: AgB25+jTG4RF6nKVMkCLecpjqIbWD2BV209vE3AJo0fcuc919OP2IgLGK+4u8vKL/ukJxqFFbByDxoNSoN2+jfZqfgRzduuLmQ9GA3DlqVRTRkFbTZuaZvLJNCISmKTa64p/yYDvF7AM7LfHtp53lEWQeaw+dwAxi+n5Ozkug8T3BDQRWgxAYM2yFG1ZjZOBnl0M/1PkqBDmDUjDz7fj4cCFS5qIJWlFLMIDvrZpIpJfZJOnDDyCTRq9OH+jROfbFvYLfGwyrPjgymCVSzP2io9UwotBXXRf4/SqHwLcoG96qrltAYm2vk3TFPGRkmQNn0cfTpnPyRfLxg+t8XcZwAvM9kwsrlDDub3+seIQ2Oq3gf/hcR6zQhBHsLsxqaeppkvtQOprerXm2jOZVZ6T7OReXudAGOwDduPaWXHc2JlcZeX+lYFJTPQgSIQRxLznVnUQZpe1jf8etPMQTGRRRZUN8z7wxq98NfcaZP0TrYTl8xqXGJwfXPz7TuS3YEtHOJdMzxwFX1NbZHlM5gdvPIb2I3w15iwHuZr8Q5UJFSMGZCLthdHikQ+FIH4INuhSQ6I9vgsrX7WxiQ863hxSzdKXV39uQMX8bq2e7bt0ByzGzY+NUXzQSyMDpYFbKr0WP4DizjdUzzrKLCKbp0Se+yp7UsH0/ZPx0Ue1Lyo7ln3SOMnXsWpXMsgvtkTp3PWpjH4Glf7gwQuTxSB60VX+iDfglUSF720eflZEDX0j8yC5Olzy6U3PJqow3pBj
    ingress:
      enabled: true
      compress: true
      hosts:
      - kitten.vibioh.fr
    pprof:
      enabled: true
