apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kitten
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kitten
    image:
      name: vibioh/kitten
      tag: "202204021142" # {"$imagepolicy": "default:flux-kitten-api:tag"}
    config:
      KITTEN_DISCORD_APPLICATION_ID: "959191057835393044"
      KITTEN_DISCORD_PUBLIC_KEY: 2a1eb3b4786bc5dbd59d1f8d35eb44f5243e959158ae75367f57e0d4f169ba47
      KITTEN_LOGGER_JSON: "true"
      KITTEN_REDIS_ADDRESS: redis:80
      KITTEN_SLACK_CLIENT_ID: "2426300949335.3310973634019"
      KITTEN_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: kitten
    secrets:
      KITTEN_DISCORD_CLIENT_ID: AgAaRhuqbu2UQr50O8OSX9NjlR8TV6Q8yL9jLcwWw32boGjwEknt4DFfBhl8j2drS8hxrGH0Rwcl7pV/qeQlVUyTFdy1dZcvQ/r32pls7qtEUZHMye6H74jGtFlSdtoL510h2QAmJiB7CSrZBCJCXHeR+Hx7npKEVh4+Vl4v7yYY1LGP4bsU5TG1spMsu3yWFnyCm7qS5r1tJfQfXGMIjpd3NnY/4s6ybQplugY5OTX0tYlv3rP7ngOF6qK2L6wfg2d2W3swwzfZi6Ks/q4GD7/h3yWlZ7Lv1/BUS6l5bXvSq5gGzAzXG0pH2khmqKloYrIqBS0WpPfW8awzAeXVsKQQcqGa5AABCQptj0JX8j9t8A1IZAi35M12ybRHwFw4sCw74Ux/KnBX/uttcfDNWgxeGNDoVOkfMlymSbQyq+su4mpjbSuuBqarrzZEBcJIyzHZG7i0vbYQFnI37mxjj3RihKQUVB7NWJBsXUwMcJzx/dO1lxjvsmzBY60Jyrgehfc4MtWT5mUxV/yBstpGOkiDP+kYJE8b/6GGvi4q7r6cWmcm3Lw3OcyHmU66gIcxDGwJB2yrsZZ8qj8q0zJW5lZxgDrMY2B5LNxNIn2E/RQszo8yJWpFUHSjYq3Iby7AxIVoM21fuVqe8Cdg77g0clAGD8qhlvO59AmWSepGbG0CpM6y0JIO0w4Z9nDm0JD6pM1yZPEIHZR+f3XVwh0/NZiL2zg=
      KITTEN_DISCORD_CLIENT_SECRET: AgCPEAKAkNCsVR1igA8FgKnAwynRxYGD2GQvDVyxT2VLNykzNP99J3f7AAkWsD4ZlDvzQcNHqLrjhOwbGl/fZ+zoDIBtW+agIM1XRQqsPis/9+3b5tvXciqgio/dC6WX3PWmyMs1ZqmY3TM97ZQ3ODbtdFwKyNz5CVtQXLT/7SuvvGDkqX9iuK6scBmbEaFguGbbv9KzdWW+PUIRulkoN+yOaK75UTFp1u/jfjpIlMSzYI3Tea49Jv+f2x9MubzCO4Tjq+76lc3DmrE1ueQhW14apM2ZKvSCoVE8oPPg1rR4dNMAUM9AdOjK808y2auD6fe/FPA/wvZW8dw+IhLmhaB1VEei6JJbiQ+KGGPhTcfYhPQHu+dQbaJGUFKJXsUJkJrIH+a/HeM/DP0kH9f7jd4Ppnz4RpgxECbIySQKhlvyWQv5Xx9rKnpvxa59ZRFoGpRbe2OhPRgB4iobgcrKZVjFUAbPYXLUN2BQWnzBhjIahy3pdeNqeulyR05px3J9oWCu5Gidj47ahiYyDqajCXSgaql6c0KxRB2Hka8V2cQl95myKFWeWiSza6dhGSq4EoR8MKkCZtWi9OpaHkbw9BiXLWepZ2nUcs7+zi6F67XtLcqHQ9/W3pRVLT/VfFcnLlpIZIg6C4NSEjkuaQjn1mY94bzR/gUHx1M7WjW4g+002T53UgwB9oqdKb0LFxrKmu1YzTjtJWQuYVrSlwMzDyxl9MM31ROiBJ8tMSVAU/AAhQ==
      KITTEN_REDIS_PASSWORD: AgCGUDWeTJcEINqtKDbac4wPHF1Inn1gspltV0a346/8OjAI2fgJCzOSmhalDpXg+HwtLm8BZErpn/hV2czJjfn8YQVEYwf2G6yrm/hODXZh4uiQBVbdzwEeFIk/+nrSfcKooz/IRTUuOKbxN/F/xJpeZb+AJ6/F7Agrcj/zFDwlRkayXvHHsCeJOShuVdWjAg5mg7oOkvDlYGRudGOe0Wyh36/N6a4APiUBctG4xU4X1gxicgY0wD128tHKYrGfMhK9nufz0jhycw8c4mZZNcn97L9d4EmNNb+xULbGrTWjpdCJt5o+G80enbx0yz4zq1ELGFj9tdoSR7zhV9Rm4yqsSZfqVfg2zKrpK2x1qOuZvVaVI3uPPuxvI7o4H1e6PViL6Dzk3fW/RaYt3GP77a4ROla2Teb9Rl8yFQf1hD4LkhiUeF6NPvEFZgcSeY5U0U/QGzGY0BPIEd+jrcEWJr9cIN2LRKhT3r4USqPad+hReTUo0vsE1VfGeUj5qBQXhI3uNKyWU6CD9ssK3GgAWRCglLdhSVJOiJkzWrN5iIamS49KaM+LbBBeEgyp6eDdykTQApJIYX17l8qTPhrmtaH5woGwH5tbdB0+0VTKXsGfxGo0VN5rUXIA5ghAfosMzb1GfO5vPKPVayDyBNxCkcmiTMpvmoURdMrSWiUqRYsxnAOIHVkir3lgnmLelsjIKzjd9a9QuZzVlqZ+syaqcscKrh4rDX3/lDIagzlAmb92ISfYbSK65Rsb6LpJkpgG2Vsilx9h7h1/knjPvt2/eR8=
      KITTEN_SLACK_CLIENT_SECRET: AgBBGoAx77MhvrwimWip5Smin5/K1P/JAS6sCo1ZEAgWEnIwu8MUOL/B0krpeNldWEh+GR3rWgxEgiJiOAokVU5SavwWBATKFcmUQdVbwwuHIzSVdoJiWdc8fe/xE8BoYLLVwyjH1H2ZIhSh1hy5WLX8mXdBK1ER4yaDc5suzqDHkijwHYNOJqQuHq4C+FVk6i2pzxjH/7Vt5cbB1Dbd6yqbxYn4lqwpfkw7oVFGbAVvCBP9x7VQFzWWBO7EfscuJUgWqC/Bquyx13sYvpFFDfSISqv4Klg8KB59GTOqP1eOM39+yGeJ0jW7mGPZqgTksA19zJ1uS43Yn7sODYZcydaPwGn9GYz5xTONYVnGGSUQFD9pe3SB6qXYs8eLKgiubUoC08rmvv2g/GWX+2zW3BuwPQnmWMKrDN7atwxZkm0lA+kBlNq95ZUVQIPQk3fEzUAyfw5/k9tG/xWdPhZ+q5Q+al9n8pdMkSNI1ibRC/YVhOgIts1XKRFjkmrSwkIcl9RiWSgPshpKu7XvWmDyYN0yzAu8TAQA7mkX2weUHSIVe+PpQkV4Dwf999GHatRaLCxbrBmsEApf91usCe8CjWeSY1o1nQWfUZVKpSnHeb0/t7DQvS6xFD0nmtVMec6QqUwONnxUlcDaJJ3eOKwlYA4WoEgfwgNe4o6FL77zB7JCzRHS5TuzzuW6HrgrptSXGl+DPVkOKKWaAnHlnnpjI/wJSuMB7diqwdUTuRUyi1gwTQ==
      KITTEN_SLACK_SIGNING_SECRET: AgCnHOi6q/hAniQERTDidzRRJv/mrI/irN0kr7tKjq9TSQ1JN4zibB4eYTKTVp2bQSKCpl+6Oz8YArMmh40VcCvcILNUcfMdAhJVpXakrI2sHQvkXbczpUPpgD+jhx0KhBwyjtrQnsQ86DKJt2SVW/r/iAhrwGq6cgBgMVLzG2tb+q2eHdAfMJ8m/hXBemCmSgkHv/8j2vl+PyvLCNQSR9HF1Bx8/BwNEJgGrORhQe1E1az4BDYSqirlHn7ma5zMk5yLVcFiPBuOk8K5PZuoBhCzfIyH2yfwGZXrb9BhJg2wU0gxPFIFqFVC6iirq+mFMV4jGmUHlYgrJIcwG2yNI6xeDR3bjDRzLXqSL6DtFohoW2tuJ+kJRMe9CLhlBT+eOLldUjj6ytDvk8RUiEdtdLrHFDhJgaJDzO3+3C/9SDY46p7vURK1qWygDnaQZfbR99qM13dczH/4cqH2/jgMe20hGc2POiO9tWZqF8VVZc2vjihhB7Pb3L43zyU0pgxbL7Y6rFa59xfkyYDbPA6uAr+klfI6SyCx491V6w77OSTa/Q2/VXL2VHZmZGEEy7Dh3DbWjW64i6O1wEJBW6cns4G0Wjc7Hopr1EBlhh2KaiOW65V0nC1HxjExPoPWXnz7GzaNGGbfmJwv1VuPuhll3A67sU5LEPuaO1qeR80URCteQxnlsz+XWvLzLBi+nAc70C8zBJ/lcwW/+YT1k1zaD/wqkUnBUKQtqAzGenh/6OiqDA==
      KITTEN_UNSPLASH_ACCESS_KEY: AgB25+jTG4RF6nKVMkCLecpjqIbWD2BV209vE3AJo0fcuc919OP2IgLGK+4u8vKL/ukJxqFFbByDxoNSoN2+jfZqfgRzduuLmQ9GA3DlqVRTRkFbTZuaZvLJNCISmKTa64p/yYDvF7AM7LfHtp53lEWQeaw+dwAxi+n5Ozkug8T3BDQRWgxAYM2yFG1ZjZOBnl0M/1PkqBDmDUjDz7fj4cCFS5qIJWlFLMIDvrZpIpJfZJOnDDyCTRq9OH+jROfbFvYLfGwyrPjgymCVSzP2io9UwotBXXRf4/SqHwLcoG96qrltAYm2vk3TFPGRkmQNn0cfTpnPyRfLxg+t8XcZwAvM9kwsrlDDub3+seIQ2Oq3gf/hcR6zQhBHsLsxqaeppkvtQOprerXm2jOZVZ6T7OReXudAGOwDduPaWXHc2JlcZeX+lYFJTPQgSIQRxLznVnUQZpe1jf8etPMQTGRRRZUN8z7wxq98NfcaZP0TrYTl8xqXGJwfXPz7TuS3YEtHOJdMzxwFX1NbZHlM5gdvPIb2I3w15iwHuZr8Q5UJFSMGZCLthdHikQ+FIH4INuhSQ6I9vgsrX7WxiQ863hxSzdKXV39uQMX8bq2e7bt0ByzGzY+NUXzQSyMDpYFbKr0WP4DizjdUzzrKLCKbp0Se+yp7UsH0/ZPx0Ue1Lyo7ln3SOMnXsWpXMsgvtkTp3PWpjH4Glf7gwQuTxSB60VX+iDfglUSF720eflZEDX0j8yC5Olzy6U3PJqow3pBj
    ingress:
      enabled: true
      compress: true
      hosts:
      - kitten.vibioh.fr
    pprof:
      enabled: true
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumes:
    - name: tmp
      emptyDir: {}
    volumeMounts:
    - name: tmp
      mountPath: /tmp
