apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kitten
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kitten
    image:
      name: vibioh/kitten
      tag: "202206171933" # {"$imagepolicy": "default:flux-kitten-api:tag"}
    config:
      KITTEN_DISCORD_APPLICATION_ID: "959191057835393044"
      KITTEN_DISCORD_PUBLIC_KEY: 2a1eb3b4786bc5dbd59d1f8d35eb44f5243e959158ae75367f57e0d4f169ba47
      KITTEN_LOGGER_JSON: "true"
      KITTEN_REDIS_ADDRESS: redis:80
      KITTEN_SLACK_CLIENT_ID: "2426300949335.3310973634019"
      KITTEN_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: kitten
    secrets:
      KITTEN_DISCORD_CLIENT_ID: AgA74vki6+a0b//ziSX2Znbbd4+5xKloGLNT6Z+U81KjNSbIrMQNJOkxbWOOmsrGrfYUp2rDHVakAVa1rIbShPlSgBgIYtpIE2EDFRzDzlDqWdoExz0a789kIWn9tM6ejwzaFKzI83GQQHHHThXgsUbPZ9dM780OIvV7gZ3mooXY4dexdCYvlSCfnObupIoL3pzNL45qOX4+HrcZ7wD2L6Doz4TszKRjs09sEsxGlJh/pp1F5wikDW7mWL+qPevrCjmLbapKYMsB0HgLtdrfVGpSluq2HHdJ4rZrO/2b/YIhtaxl0onxL952V+XsFTsXg03BAWBQ6u7ijVf9pukaA/rCmKop7NXlseWAsdJWmkumaZkwCZZ6lgmzQePQyB2ZwbQ8KKTzQjgkszXDAcaQiDnqOjlpNYv3sITqPm2ZL6F7j4XQ7cxn/ux15q3WCqzlr8cCQODA9PwHydmKUYxVQFhAVnbF2vGtz/fVkWG4vPa/gUpMbsUA0x30C070tL5E8lJMA5OHAy2+c2TYk804eDm7TiaEEKlIgVgCh94Xo/soDwHtDtjEbI+V/NfktevtW29WzdlrC9yxlXuBnCWtZCJzp5fyf3nOIAqgAxNR1AavWKpCdEscySMylgaU5kFl+/CD6fY/zULFsd4B3VvnapDOU7eM9KYzqvWrgB9wnz85+rRb5ANeMTmBrSe+4wmD7Tt5fXeppIm1tLrL7vVURfsE7Lo=
      KITTEN_DISCORD_CLIENT_SECRET: AgB8Ma86OOcQ5F8kvM71j3sy3JTbOavq3NvpkVLRgMjS3W992Ev8gZDRsmuh33sajUEX6b2LhR7kBN8QTA4UsZNgdSm0Wo0BlXVjR0J1I13S+zu++MFSh6dA1WTx/Vkl3A8arKvUgEkJD/b99oDY7YnJu8XlsXuZrR9dHq8zF3blzei9DdTTocsKbh/DAC3OQo4Wv0GtYuDHehKdxuxjhFDCY3RpH+lS7Xo08Xpq1rCBiuw20+PwTaEWWR8lb1z49j3LC3oSJCM3Gjv8G7QoxJDXcvZM6xi1IEa8K+8FXGAct2PXpyj9bhUitZuumUh7dgY3XWlVzkif/8H2urbL75tlimqs96RgZt8eJ40l4ADNA+tU6XiEo042kSqD5Z5kaTJQVRzr9Fn5ikezAQ5kNvYR5U3k78PNZpM/KSx/pZ1KrFkTRfpUVUKUicf8xTapIXzuTrpExKGpPHN/6nfqWGGVcIkhLPNf+wGNznA6b5hIbUDdEITYFHl7LXd6DpZwu8NgroFoFFGXYy5jKNSzKVKu7e3J2laNcfDqGeMHQCIpfEmyD8BacVNFKL4QA751Y+Sy1PBMYhEnuoxQZb6Tmee9qg7ph3Iubunl75wcycVthI3bJrRWYQuJgS3fZC3NCxPYbtfPG3fl7B0y4cd3PxuACnzVZXc/1kieFoaTurmxn78fC0fDPSeoUtFluciDx78oS5rxV0DyQeDDsTmBUfZ8KXTfaSujgC3rMmE/pEKmvQ==
      KITTEN_GIPHY_API_KEY: AgBO450pzs/tCweo4BkgLCCVzle+b0uGK2UpPI2b2UlKagMTfFxoyn0z9BUh0oW2PSLpGsbOPXblnyzkq09+K6+PfrMghSCUB/4oqZUO04NgWCSLV4MDRg03fTdBizN9Wa3vRRGH6dVq3FlFhXWxwUzaaUyzbvJlcc4JsXLsiP7KuQLCqzx7M1rhBaODxmxhIMe0NSY6NKpK30g6wi8OTDFV+zkXWAKJCcLfSrGnBkAtSMMNXLAEaS7f+yLL00BPSEX03fBh4T941KZhGmNlq4v04ld0tI9sVZmT28OIuS0KwKFMqFplFsWhEWsNNV6q18X4YF6lh2DkvuAAlO8xVNb2BO6hjRS+vagM9h/RvzGyKHVVk5tYAzdPO8hLXb6XRmFyPvKpoOzvAMgtbBadI95930G68co0ClQFgDAnfLs16WY2EWi2FVCSDJGgi9l81efWlJHuo4xLvAJK08cG9gtTTry6ranGeq964/MFdXljjERHN0h5YckQAiiZ++1reVCi/tEOskyFYB5s760rcNbcXxH0VCJcmK41UrRdt6pbQ51fC3KeAqVKr+v+YxlqAmIUAljD9k75awsbEqclXUHlVmxmsfosYZ+/yb2hOIVAs4B6GUGWIJNJj7SNXIYJtOEOkCadqbImunCNkHumKQKLvbtVvqP0bP/y9M8suv5MRfS/Q+eFsZCeiFwwEZIXYPKd1tfNuX2WLn+StTG6MPoHytn9Ah6/iUARD/HkMJ4S6g==
      KITTEN_REDIS_PASSWORD: AgCu03ngNZ0V7TIuF0wTDR157s90BJmlFrSLVp4L4PqVs6wJKM5nUl1htqvXvJi7YJgtGulPy9vwrbySPudK3qcM9mSzteJ/hTEAYWdp0kyNbOuf7HeRk5A+6EDIScWCzMqRWALMPD02g3egMG7W22Ygh3hlSDf5rddfzbY4LXMMsEL/TDjN/mxjnEcP3g8DAozPyu7aX2RhDsSmmLjhIVKiyswqYXBBKRqbqxwjAniovc84UKBxfayZhpgotZz2t0ChJO9YXudZGWAmTuzdllqldq55CQnpeY2HDlY4LdtBnWx7+Hafuyhl2cnJQ9pLQ6uAHYo7hN0udjXqBpd7CsRvr4UrqTNEem9+bG2cTE8QO2OdsWArnhsv4btXUSPiA2DhGGZmTkwpwxGssb/bLK2OsgebwdIGY4oElzUwioVTSH/q+JI+F6G3owLukNzeiqws5JWC7c+69Yw3BJA2VU6V5dPSyEE8vY9jmE6uAwr8JBRRltJwy6hdQOMR7/p3MpsqkxFDTusvIiV2A927zYUMJnQqeEjwvhQyF4/O/D/K81S50JJZoLVp6XGQyxzdbiKyi9h4CrphMIXDjtBs287k/iSLto+ibE/xHeiVaG4nKM6q6bagxqutF15fDbuiV2v5kJ7qbsjV97NK9JIz8Vi2rPV3Ui2bJCIjPb13U7/N2dvVz4nbC4+UGKto5z/5JvfbxZNNP2ymE0RN0CVUUawCai2Gzz+TBJgBwaYDbMavW76jM/HHjU3TENUB3wci/V90dfU7wt/+gfsPYjxE15Y=
      KITTEN_SLACK_CLIENT_SECRET: AgChVRKejghT3QiqSry1dIZO99PsoJlnuVQBhj/UvJuNKjhjy2EC387DYGkWeqv+aiQuJ72PPiahDGe5mXoqcrt8TymfzYGI7legRFgAbNM3uf4g931o9yYLurn1ORpRS5fXhDgIigFFzF81Akc4R1zqO/TlqmQw1dWvx3eZM82wBMqu9O0LyH9JT0q4uio012zOgDdJrLrZbCmnkPOHc4kBO9xt0XobxfEmRzQ5rVRYTm8LWVlZ6pZhNf790PIq76IT9VPlDJVCZr+RCJOdngab5fwQOiSrAvTcwrwDn69CzF0f6uSGD63RiJ2bBUaUEYD6w8oCm4WGFxmVy/gJJGm8HWtyO3NI3jLajCAcdxL7yOFtPXCSshB2moX9eF1+ZsK2ox3aq/l4sx/SnWcCLxSK+ZNTimAhyBQn9v6p2t1zaLvnEUU7N2CZMU63i8SWUqyzSkxoLNINovos5o0xag1mOrirF5UWoRe2wZLpT9OaUooyQRuVJXhDzVomY5MItPdQ2bZZB0Td0zQVSfqEZV3GxP1WGHQ9YWE5Y+j+fNoLSt8vx2vMrxPqWtm6w5AuGOPCbJ6sNQSiWbUUNqSmixYauF3L52BGNBdx2TLfcVUPLeZ5bny5vFM/pp1jcR4mGboQ50+Fk7Y5C5u1q6uB1oOyFBr0BM6eeGJ+zcKJR7VGMESsuxOuSCsb8mNF1bn5L5vzqoB5Sl/zN4UheAMwuaIo/WtIjEIr0wQWZTmZPYRnwA==
      KITTEN_SLACK_SIGNING_SECRET: AgAtzgdFS2x28U0lpyB8v/V6phmf+9nMYOn5ImfLjaKZJtdKGzJC5dnTlfMehRaWLzolRmEpvElqVcG0AmjYwBenBwZjTBf0fx6eVDhnEP0pl0xwfp03vY96h7VNltJXBUP2x4A3RZILfryvwJONda+i8mdzzQKABrJWzpKPv1LFrHaoq9PYQoNstRNQmBhYyLJvjezyYVbJcnz46+7oo6vPKSd3Ff5EAIucFfDM9FAs2TLYjz+QkreFKKnP2ZHu6416HV6c2uCCeeP+ONV2kPKLo8e+hLSFkkJlMdu40OYxE/v/ZksvZdE3inXXiI69VULjMFGQuXA5tr7RclWtOf7UT042YUiIk5YGQ7bVot1URrweJ9G8k+s/P04F6gm8WUityQKeN8q+dLNLxH+amkqwJaANDS/Vx0il2gJr4Zc6KH3nv84HtE+yDJ83mgkKoxrpLpIoCdMuGVtOABKKE7GbRlkU106BixMs8sJErhjnNc6kwLqKh4IXHEriIyJ5xnsdrtyQgJ9lL0h+ViiPkrY2zryyH8uQYnygqMUhcBgc+aNK1Y56EYmdk0ehS6N3fsHoFCjklX7IFRM59re6gjOvkBOSG0PVVlWj+UbtCVmz/wfTKLMMPpbrXHTmmKbUUQhr/6QiAXpjdxvz9pIUZ3SIrK7KdO1GJc22/AAWvPVdiiUwvYiQR8jbT8IFoDsPqZaFe64dMC6p2HIUSQKVoS7DgErZC9Cfkpa4nwV1bLiSWg==
      KITTEN_UNSPLASH_ACCESS_KEY: AgASz2TLPL7jG4rw0jO/56gnH/3x+27QUgRnYdhacJAep0jsmCKFCiWMe+lD68eYoldTrev4J+OnWDClCwS72N8cUqM2dTvoC+ySMj9RBSjMLnePq1WvE3GkOvOyqgUTzv1On1FqUkXWE+OK7XfGCnVZXeH385kSbm2jwqnqTIzxrYWyDU09taxcsmuy66m9CB6ICyev0w4EGmvwo7XbABaUwkA/tHMT2EfWvMnaBn0jbinnJiQwYnVuCuXCwvaGeAyt5JrnlDfWcrE2p4Jyc8WTszB5/awSQD6aKoPHqc5IRwHCDO1nMFohC4dctgCB4SlZiOUHEWt36+Ddpdqm+4RnGN7xxtUx1eYxa/24XEWbGnbRAaEBz2VD2f2W7q+Xi2dNxw43Bmma8BFGK7enwqts1GROYDtJ3QZC9hpF8+oFoEA591X5t7+wTBuFq5NXZw//Mybt9i3ciFi28VJx1xyPEP38f0ZkOe1R5KRjwZPFCjt9gv45zry0SMKsw2FkQpqz4/p13ZUpmwH8sEJcfF2R56SjD1HimedWkeim0K2F/lvANb8Rd3ePV/5EN/2m3Oq8ogdhaphlhldZiJs/abEfNvM0tYvaWofz4hSBiW+l8uoKAUxQj7lzmTydyr3Zfm5iLZi3EiG2LMP2MzI21FdGJVdReyYJRTmh5oVtH+Todz4brZfWZbd3q9TYLiYueHaEXWY1n1cUkbGgogE9Yj/9wt2Ik/j8lHmnOET9uN8xUVCGEoPlb29Ytq+G
    ingress:
      enabled: true
      compress: true
      hosts:
        - kitten.vibioh.fr
    pprof:
      enabled: true
    resources:
      requests:
        cpu: 500m
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumes:
      - name: tmp
        emptyDir: {}
    volumeMounts:
      - name: tmp
        mountPath: /tmp
