apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kitten
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.84"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kitten
    image:
      name: vibioh/kitten
      tag: "202207160755" # {"$imagepolicy": "default:flux-kitten-api:tag"}
    config:
      KITTEN_DISCORD_APPLICATION_ID: "959191057835393044"
      KITTEN_DISCORD_PUBLIC_KEY: 2a1eb3b4786bc5dbd59d1f8d35eb44f5243e959158ae75367f57e0d4f169ba47
      KITTEN_LOGGER_JSON: "true"
      KITTEN_REDIS_ADDRESS: redis:80
      KITTEN_SLACK_CLIENT_ID: "2426300949335.3310973634019"
      KITTEN_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: kitten
    secrets:
      KITTEN_DISCORD_CLIENT_ID: AgAri55RfDFVAxYghvIXP6J99ceDiuBRlymJQr0AOUrn7pJovsaeirQsGHF+4b498k+2hK3U8Q9fU0KLdzNSFckF1jX4oPf69/5vTpwoFPUjRyxBVe+lcNIKnsJIVzoJXTOIc4D8RjGiblzWNaaiw5I3wbfrUBiDAT0dq5ZvT5keHdQCqZMBsM6pevMJFyrvs96EoSFE5II8VT0u3vmuGQtwmLRpg0XrBYfO4dFMugj2LlJTfx/JNsB1UBFcDXh3zLhZrYkTffMfFgUvL+o2u3DYTJfbcfqyjWrie82OreexksGmDPo715QwmIbNJx56t6s6ctNzWE1MNIuf81y8sQJ4KsqhfeAYRJrBvt4UIJdB0HKjZH6uq6vRoKIF/4F+sqw7DOdV4E8+cqq7juOgFnRwrQ7gzFJuvSedK3i0aUt+B3C7nKh2vYfEQYGrjKI18KE9DeupDSgvh5DuDYEMr+V0J6dw7XiTl8crBomGSakLKYyKASm9PbVht0JG+69wEMZUwtvZUiUF4I4jY7fgVOl1+aPAMVXi1ePb+qbvYyejM8zJGuqn/7W4NLwW9hPzh7ai14UVQ0MVcEQaePri3jD5tRknCmVT2nk0xt/GNldVVB123XGyeaBqrlBWYr2I8KlbtLWxuAtynbyVagDoczXJhfnZqL33BGLejmTlSpHaH0X16QlUHv7K61juiG4i1eaaxMp/CxGF3td8UuGLC/iBZMs=
      KITTEN_DISCORD_CLIENT_SECRET: AgCQes1KFhtuPIZ5P9voZy3Jdmcvv1MHjEkqfWNJDkGxH3MBToDMbjvEi1cvUD7lh98sYrH6ZaVNmtUUbpg1UZXRPdUCaq1c3ZQuXfM0DY61HAqVSxkWwFaQ6STGQi32JZdvDJ1BUtCduAygALp3+LcPZL9RymWYYj1UerD22WG5Tr+lN+i5BuiDwz41MBV1mntjbXtQ2ri2v7Zp9Y6dAAAZenlSbD3Tm9il9c9UViGLPUDizk5G0HQbm9I6HAJJA2YiyreVj1yqB9asHReRNa2AOR9iwndZ0Sl2064vMkePyvxpf4GUh6/gMtEwH3Sv0uSktDPvKRN5TwXXmcp2CKvzFXUM49bFjsWrRQPxmDWtW/QicZM3ybRA6OA/lXMhh2s0I6ZXezoHfV7vlRMkUwJQgjnTLYm0TfD/nNdNGR5h17ogRdQMdRzcdfF/n4piGFoGadjHSwh+qJFXDE+CkJhL1Bm1IIE8YsAC6+RzPsjuCp95Jn6lh94ro8t0vOSuFRe+2ZP7H9omE9YM37bSH4ovdjeu7EeM710ynBoy3XhRdxdK8SAOPYCOO8Ih9EnVNvYZtAMM49u9zkISlfDKGh06ZCQ0NYUgdgf9ZebVPfp/73FYEqVHXi+5LomzXUqDQajHJwVC/vTll8OR0P5n3zVWDk2tqPGA0uVK74flDLcMxxPaUYaam/3b24pU/5uXt1rPD/B6PUpqAmmGLudb/lFUpm8AeNz5ui6N7MGXABadTQ==
      KITTEN_GIPHY_API_KEY: AgCwcnWpwFQ1XlQUEZ3jDK4tO1Z2M1E+IsvpM1LqYQZsOwwPgUNgk9JUtw+l26x6fiHcJ1jTDTzgcYeUcDRjuABvYD2EXhQ2vBFlUyPDf4i6ui0OtgNHcu9F4pWCeyWR8RMZgma1wtnjpkti6lv+Vsov0TS+0+KTiYWC+7bLNXa4B/gR3xMS1rbLL5sDM2aGgLNxAi8XWEwru7ANK4t9yXuYtr897wdG2Hiv9PXzhDqy4NGihWPOFbk7GGTruq/lPFhpQOuzROSVMUM+S8NbsqaQzxba2d47eF5nq0tPfzjpZhwebKLND0BxjvhVa7WjSHrVYA6nORhGzyr+lFnb4GjAVuh+EEGUw0EstHLHCMOW10uumXogSHJ8KMSpA2zmSMXlxYzampS5BQ3SgOStRZ70fNrZcA/vKWvV7ipA3KHPxenFQIpkLr5iLN7aRDHoZuBPh1Wg9byvKBaE0J9dFLa6O3SWIhAuBc3nBkSfnHbPyOhbPuh6mD127JTiu/5goS2jgukkrDINdC42g8lm96GrGAwkXv9BcrUzGCDAbhtzv6rdlJ5cBR205QEcS+/zixWcfnv1cl/SKJzPDf/eNfACKaHfmlD8D4S+hLxaPDJ+nbjLdmUN9lLcXqsfFVFwVh9cp16yzZSUs85BnwkmrLHwASNxFuQAayWSF31dP9kd+kp/k1ZmZrmBO/M5cm4nP4H0aJ7tqqsdXV8cpKZMFodheDWrGW1TOcJ8BRPihH2sMQ==
      KITTEN_REDIS_PASSWORD: AgB8VQnDk/GFxw4G5YVxbkD1ABAV9CqlFb1rNZ/7JNt15sChOKxIpoM/Oc1wzJ/U4MhNYI4r+I65j/4bDtIZvurBbbxSZcqMmoH5Bb2NFMNcoR3qqvSOrAiYOfocKTDllSO+QGWFBLdgrNXuxuy+q9I1OmqzrCPj1a3rsDBTrmonC7mPyPFPtLwR+U2gDAgRjFN3NqX7+oo2OkvTktl2WOf4hB/hhUseVKvpMBvBvqviA9N2ZCNUuyH2Y5IEnIXGp6YNi5tXgidfTaUvLDt9DdtOZSXAbdn8hJBG6Ly0fIKBR8dTRf/CM0dKFyusunMcZTWLYzoO/QeatdJVIodLh9w2RNC0gOf9+hGbvS7WWnfQK7YclBoPbUII+8sYw5g4NkGf17cJaB0t+BTmfV4IUUMH1UZ64ymzvWtZA8ziVcMZliFOYlHUTr0IiRaOuGEmhgU6oEJTOTB7AcIfnMECvtn2LgimVo8vsmEn7IIGb4lmhoNy/BLxDm/pW53FHIEbTBOus6Zpq3yyOfPXHZWmc7wHkFXjdVSbjgN6iOLpedlpNcXh/QGE3h17LU1jfxygR/jxVyB+Y2rwz0vwqtdEZ8FC/4rGoeHjix8fk5z6IS7F8xM/OjQ1ep3QuUruPjPPSIiPaPk47K3zX/jq5PPtlXQWB0gt8tHg8RACajXjQ/Ee+uOT4uVlRB02EjOb55N28yn0gc4MuYwdkFQK+dyR4yoYRckGyzxH1gIhDM3rzKPgk994iKGk1zx6doBYlggjKDXvoC192XycLIFjUbc67OQ=
      KITTEN_SLACK_CLIENT_SECRET: AgBvkU5qBdxwGN5tNX99+EtamPLqcTzVC251OOYEA0ojhqh6vJPzQvYKP5MJBINxEYfVa9BB/jgncYvR85UjrS2MJztV/elE3W8LITS1ZT/kVmprcMcP+fmCbV1ZoqXxGybRb9BrIdmYDlBraxhhCv9IVbPL4abq0bkRjx/+Zh8MiODT5TVrofbgoGO+y1k04OzXjpR+KQ7I+I6IPTv02NZ7tOFftQQOKNk37BttT+FvZNpi6A5y6u9Mok2+KKJchTWlXUNqQS5lD5b1IQVcw9x8UA/GxQV+aC7jxsI5NL8SgqmTP47QgcFNkcodV1z/5cs7vmtWQVpxctKKYXkqUwKntoiLlljIUMXDxeEjjwWLIriX2zfYKK/nb96GBktKjh+hzL0kA1+07/4f4S5ygofgACYXIv3YhZfcNCdYHgQBeKBHxCR9FvwKqv9e33etuDgGMHC33jbooWiP+p8aGgZN+wyFGGmZDDRzjUN9bU8uDFhBLLiyIdEAdOf1FI1MDNPmLwhroI9ZaZ6/T6IPTrx/I3dnMwAegzVsUWeHuZPxC/5aPONi6yVcrYmbK9yCM+oA8j4EsO3d1Znc1p9UO6UlPUfa6MLqkjM8hv4Y3X9CZJSr7b79Fy7OONtY0XlL32sssxTwWh1e84ChTjP1dmZ/PMh6aYX6+ZWnTofenbLMeOxDrefap+FkmEu1vqGhA8lz9ZlilvBICHYCVK8lyqci6dB7IPKXoPv58Hgexqkn5A==
      KITTEN_SLACK_SIGNING_SECRET: AgA7NpraSxatgqZErLo5sGaI/PJYXNMFsDttLLTiSX3XW8mTfXxGmfvk3sGam2BJvFX0vuqaDj2aKLBvqFfI+Nhoz32BgceORd+h+IKgDDKXMNVg6YDtxLDcmttaAw4Hcgie9abfHFaAVFWO9b2im1BKU4HWsXUEkqcKoqgbwqIyupoLB1rhOB0mCtiCsybi6Ed1pOO0mFyEYd2bbSvDTau5RUhpa6r7niAfgjSW21BoMmAajOszl0O3i/T88/cshsDclqQNESDp/pPfNCDqxPgb5a4fLRO8s+5Db6ZgDgm3MCbZOQ1M7B2f5IVq8joH8goDb4Ek1HnKSj3+5NhiuzOTqDvJJBET2lvbzLLfQg4kDfXGj39aEIjdN8t0CguzSfuvgvqg6lFPl2EzLXshGfYa4CzUvutiZ98ZjOnfSnTyLtpHeF3jKzyZtjhAuxasVzyaLM6hgrvxEhJlU1aOH+V4lXGbJGUaN1w/z+QfdCcsFAbojn1ARwZsLRn5puMl35Pyni72+vIF4wIOhonarSuSS5OGxK68IvZiu7oJtI7QuUiVMm03Xn4nW43/tsiwKhbQsQAK9CZRLg2P2ZpHH3fWlWwWuwNT3Sa9vkYdeiNy1/H9ThPAui1EBso5a6NRoLZtjxIsoMISTrdhVRTA0jxBcQVWH2m2IFpii5ZxMq2qpYKT73lzhL9SsEDta8QGKrQIksDYBkkjixO8kMBhkt6WKQJkHydXyEewJXeFIjr4OQ==
      KITTEN_UNSPLASH_ACCESS_KEY: AgC76N2bE1FgxRnOIQktsam9ZQVRFunPIhwAqF+PX5bwnpGgEybICBH7nbxH+9r12kfxcAA6xAgWOc0tXgvGzBWq+z0WjPsfSmAShcAbJbM5UmrGlabCLs/V3ugNiFCnyzd3Or06keBgfLUfawzEdNcdPMYn7YrTaVsoT/LDme5fnlOFhJM+zlrkSWHE/2hvKZDT04/Hz/zFFarw/EuzWtHaK5R5XQwpPK0KpK+al550B4F+DvGKKkzN+U6E/npN2XOSzsBokuXfXXZS5HtxOiC7YEdD/LGAYRRzAm6slRfxP15MjdPIhVZQRnACRPEtXJ2yapRpWLGG0/w4ogqbUfZ9GYl7m54Zayr2yPh4Uo34cQRN661DVQxBBaaVzYPImkU2cOt2EuaW5ZYmmuhICyEOqt3WxifvJBs3ACmIg9Xxq+k+3uzXmc0QC5js5Tg8Uo+hFaG46ODZpIXdnkZ6q9gTm0rgWPkEWLtRoxVeQGBeXIb5unrOVokGIvNhYMbflLkNCgErIo3c735V0+etOPQ59e/j/NWB7A19KPcyUnrWVpwrMWKZliMp5sRBc6VumKiETWT0PPl36XyQa0xbduquTGFAwxQePNMYrlI7VrcdFdwdkOLXjc3E+wei7oltQ0wrRB9mejXnGxA2dVFW5BF0+2zMz0s3e/5o+gHO1eOF+QDhUD5nYGB+5WCh0EzUcBiQaUJwrmYwN9IVCuYpTeCEAW5SeQ0MDS4GyWmgYdUCn9m1cTYJ4dOVQEhS
    ingress:
      enabled: true
      compress: true
      hosts:
        - kitten.vibioh.fr
    pprof:
      enabled: true
    resources:
      requests:
        cpu: 500m
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumes:
      - name: tmp
        emptyDir: {}
    volumeMounts:
      - name: tmp
        mountPath: /tmp
