apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kitten-discord
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: "0.0.16"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kitten-discord
    extraLabels:
      k8s-cleaner: "true"
    image:
      name: vibioh/discord_configure
      tag: "latest"
    config:
      DISCORD_APPLICATION_ID: "959191057835393044"
      DISCORD_PUBLIC_KEY: 2a1eb3b4786bc5dbd59d1f8d35eb44f5243e959158ae75367f57e0d4f169ba47
      DISCORD_LOGGER_JSON: "true"
      DISCORD_COMMANDS: |
        {
          "meme": {
            "name": "meme",
            "description": "Generate a meme with caption from Unsplash",
            "options": [
              {
                "name": "search",
                "description": "Searched image",
                "type": 3,
                "required": true
              },
              {
                "name": "caption",
                "description": "Caption to add",
                "type": 3,
                "required": true
              }
            ]
          },
          "memedi": {
            "name": "memedi",
            "description": "Generate a meme with caption from Unsplash Image ID",
            "options": [
              {
                "name": "id",
                "description": "Image ID",
                "type": 3,
                "required": true
              },
              {
                "name": "caption",
                "description": "Caption to add",
                "type": 3,
                "required": true
              }
            ]
          },
          "memegif": {
            "name": "memegif",
            "description": "Generate a gif with caption from Giphy",
            "options": [
              {
                "name": "search",
                "description": "Searched image",
                "type": 3,
                "required": true
              },
              {
                "name": "caption",
                "description": "Caption to add",
                "type": 3,
                "required": true
              }
            ]
          }
        }
    secrets:
      DISCORD_CLIENT_ID: AgASy6wNOG9d/4M03A7VF+M8MqxalGeGZdWMfHvd0zOoKk3ip/ylMqeZ/FbSIg1V5V5InBXvnrrkgtEZMlwrQzY6ymU3sFmJay664nM2vs+PfbgwqSUd7DuFtvn8bk1HcVr66POSeuE6i+PpE5VfnTpEFgG2MHYZaL6VJtgOOAUiZSFD0/lzmna+1R2uTs6SxoKLw4BW2rSjlzYjXXvO4na3e4WdKYeRe/LvX/gOKvll8MDYzfu+7b4uojKucSqGP8XWTiQJ0n9pqbhCd+xxJDdRlftHEXpu5qDU4sDZEjo+gd0RPvqVfxK+ijuZMBlUNkULTlwm7Jbq1SjKm2FRRJLmLGRpwYXbzRdK26v2C7DrAQXVx4oaFFjnslsusaICzPl+Vhld8AfzzvJC22oXx2jyc7eSXOfWwz49LGeVS/6sMxO6oVZoz4VeIfNFXzZlXPffmhnZ52md5HBdY/0fkhMdFzQopPvi2kAL15pLkVGBJLFB9fklHFgxP7N/eP6G6QvECsFC+uWquFxNLNgAxPXfVEXO/G9LPffN+zAl97bIhHG7AkkUgjLJSaDRRfFZd28d3IEbYGI4/ADBakxKAArSUiQ1JIa8LWsiWBfbQKqLtfvebcWnu/FY4nuZKMVt1FSZ+MARYHzdcI5/551gq4UosXXLX+wbcRWpImFznk0kNHPlIAysr7/iDDooln2ts6rs0AN7/e6HTSxl+q/q9En0FCE=
      DISCORD_CLIENT_SECRET: AgAat54jQfe9DNmkwoBeHaMqAQ78Uzc/cWHx6gS7TcVoHxiP5NhLAJIgI8irK7HFlJ6G9U3q14no9FRJfMxw7zxCbypAeXOjjz1RgGQA2PKtt3mXKsk2y4dr1ZkgANIASJsY+mSEGnpLfO4GLiNUVlrxsVamwyyhz34I7KaeKMBFiR90+DBIfm4bkzftAmdvvSvayDSMPFDQJtE4lWXL2Yw9YkgP9BMK3cd+1K2IBSxsictdYnPN/7KJMHu/95U2yn9ii3bqH35knZMhmhnOpaOV/DKnoEJDcViSDjnU9BdPW692z3VFuZHX546Dp1XtO+g2YXOtIS80y4pH4zEWxHK+ngun2yURxD9WIwkbcTQjxOZ5iWBRf5mIZhxe1ldGsXG4nMJANzim9nArNTw03e8FM3tr1xE36ozX2s9khAD8HUjYM0JPwKRe+v6A3RVxFtmPRLZ7Xy2527zM7VIfMUU9VuG/fykzoWR9wrwQqJYEF8cclPgE1JpLUSdQgdy1oHDJfZN9OqoMHjf5ewQuHhdCTyt24qE+snUxMM/WyEfkyDEj0fPM/uiaZkBtnxNyl62O9t4RNHeWEq3BJnh1IPKsBBxzYsmAe9vLPO/6BujEYANUZgIi07ZltKqterePWxRZSQ+8UDGOU5sX1KmjWIKkIPgZVLIq5MKiCFOK3wNAd9geJ3v6Vg8t8+bjulB6hzKg2r15d+iHmYdp3RY1FSm3tzUXe16bYguTqTH/K9mpvA==
