apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kitten-discord
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: "0.0.11"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kitten-discord
    extraLabels:
      k8s-cleaner: "true"
    image:
      name: vibioh/discord_configure
      tag: "latest"
    config:
      DISCORD_APPLICATION_ID: "959191057835393044"
      DISCORD_PUBLIC_KEY: 2a1eb3b4786bc5dbd59d1f8d35eb44f5243e959158ae75367f57e0d4f169ba47
      DISCORD_LOGGER_JSON: "true"
      DISCORD_COMMANDS: |
        {
          "meme": {
            "name": "meme",
            "description": "Generate a meme with caption from Unsplash",
            "options": [
              {
                "name": "search",
                "description": "Searched image",
                "type": 3,
                "required": true
              },
              {
                "name": "caption",
                "description": "Caption to add",
                "type": 3,
                "required": true
              }
            ]
          },
          "memedi": {
            "name": "memedi",
            "description": "Generate a meme with caption from Unsplash Image ID",
            "options": [
              {
                "name": "id",
                "description": "Image ID",
                "type": 3,
                "required": true
              },
              {
                "name": "caption",
                "description": "Caption to add",
                "type": 3,
                "required": true
              }
            ]
          },
          "memegif": {
            "name": "memegif",
            "description": "Generate a gif with caption from Giphy",
            "options": [
              {
                "name": "search",
                "description": "Searched image",
                "type": 3,
                "required": true
              },
              {
                "name": "caption",
                "description": "Caption to add",
                "type": 3,
                "required": true
              }
            ]
          }
        }
    secrets:
      DISCORD_CLIENT_ID: AgCTNRpNzzWbA8sXfdYTCS8n3alVDAd8nWkyTkWz5aT5RJXPeOSJU5PzbmusSuThmbCQBtmnb7I0qvNintwrShV0KCFfhYIL7O0eMEWylFKiYDYzvJurlIOVd89x0zMxoas6LB8rH6T2oqCJ7PajFoKR/9tfesbuiQbQZj+3fX4xPl2vznG94h0ZhB0DaiW/taLz/7AJfnmY0BVm0hxkMh92FJpG7cibu3zfM59O95LFEaAKDrVkR/BFM05sq2KwVRnXu9/irzLezlnWthqiqAJ9Hl1W1qXdkug/3xvlA9q3IyS0VBPZCqSDgYzoRHer0/9r2CBV/S/WXRcOcOPC4lJD5TTwN5EF1qiL43mWdIXfX/20CUmWiLV7OMugQuvZ3/wL5uIi2a0L4sZ3alO/OsOpUDq0VVhg26QaeVRFSZjPxxf/e4WTYETLM6w6agVE4stQs25XvcqG8WSemDVQzU0NIwIL5ozB2TbBFV6ek3d4KfV8R9wr5a/q5gmAGnQPMmWEk9kCN6Jh6bGfV69cWkz+Do+0xPThlsufWgDaiprKAKjBuIuRHZ6A7EtDCSbawYIZLQ9k1Gprq1sFkgzopbUrei+/W2tUry3xrH7fgjTs6GUPwriePUqm0LuwWkIZKqjm3j3sG5PSpQ+EvfgNmQeVSQ6zcqAV3WTSTiNmMhcY39GZSITyD9EIYxQersBqvsryVnT1PYmYmkWRqZmAW9NrUNI=
      DISCORD_CLIENT_SECRET: AgANWpLqKSWeY+NAW7zjsM8gwYbjK4E6b/BUbFS3rFutkbJIhre4wsbpEPEL+I3Jo0cdf5ejluNuw3GqN9wTmT9guH3vOx/SduSIDwfXotn+KfB1NL8N5e63bhANvB5XB/IoPDxwWBw+AvpN5P5K9A/D3akz8mUuqEb/tG7bgoI4Mm+LSdnfXMjQvA/+3CA1Rp6Q1b8jkkeTlf+ke+WkDrfffde+nPm9ak5a0BX18/JI3hhJIe2GM4Ut4wM7CBNFXfbwfjII925nlFiX2Ve1XZCFZ7xPSsZu+mryu8lvT+xs9rfWansbNBLw5KlAJccRB/4G0X4ahQ3qSLeKYvGpMSl3ew+hEp7NjQLRD2cl7EpiXV1/ciQzdKm87es9VF0bIUzs/SMxYDIodzhjBo3bU+JooXxu+mOVEM4Njp7ImoYBPF8iMZMqziF/TKoQzIIiQL0Ux7Q/HVgcoIcdb1KCxfqOebM7lM5JCEwpdDQzslPbJlX4OMgeMGPxBeXjowZI4odY4NP46EKJRcCIrfVjdK9IWSAoXO992VCq5b8xJFVUO/L0Y+y/soC973s/in1/AaMX3AnrBuJ5WtuftnStuzLpHk9t8EX1QmUwEaF/VcdNN8G46yM3qSfhX4vyJPi+KDS8FFUE8R16CcD7MMqtb47892mHFVUizCQXFXyDdLvBfxLewQVf6GvMOVWq0KaR/iwjs285Yz/EpyO/OFqLdlNr3tDcpY3vEPUk8ruRAvHxXw==
