---
apiVersion: batch/v1
kind: Job
metadata:
  name: kitten-discord
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: latest
    k8s-cleaner: "true"

spec:
  backoffLimit: 3
  template:
    spec:
      automountServiceAccountToken: false

      imagePullSecrets:
        - name: dockerhub

      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: discord

          image: vibioh/discord_configure
          imagePullPolicy: Always

          env:
            - name: DISCORD_APPLICATION_ID
              value: "959191057835393044"
            - name: DISCORD_PUBLIC_KEY
              value: "2a1eb3b4786bc5dbd59d1f8d35eb44f5243e959158ae75367f57e0d4f169ba47"
            - name: DISCORD_LOGGER_JSON
              value: "true"
            - name: DISCORD_COMMANDS
              value: |
                {
                  "meme": {
                    "name": "meme",
                    "description": "Generate a meme with caption from Unsplash",
                    "options": [
                      {
                        "name": "search",
                        "description": "Searched image",
                        "type": 3,
                        "required": true
                      },
                      {
                        "name": "caption",
                        "description": "Caption to add",
                        "type": 3,
                        "required": true
                      }
                    ]
                  },
                  "memedi": {
                    "name": "memedi",
                    "description": "Generate a meme with caption from Unsplash Image ID",
                    "options": [
                      {
                        "name": "id",
                        "description": "Image ID",
                        "type": 3,
                        "required": true
                      },
                      {
                        "name": "caption",
                        "description": "Caption to add",
                        "type": 3,
                        "required": true
                      }
                    ]
                  },
                  "memegif": {
                    "name": "memegif",
                    "description": "Generate a gif with caption from Tenor",
                    "options": [
                      {
                        "name": "search",
                        "description": "Searched image",
                        "type": 3,
                        "required": true
                      },
                      {
                        "name": "caption",
                        "description": "Caption to add",
                        "type": 3,
                        "required": true
                      }
                    ]
                  }
                }
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: kitten
                  key: KITTEN_DISCORD_CLIENT_ID
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kitten
                  key: KITTEN_DISCORD_CLIENT_SECRET
